### PR TITLE
expose topics via public getXxx methods

### LINKED ISSUE #1: Add public methods to expose the MQTT topics (for display on the LCD screen for example)
```
getConfigTopic()
getCommandTopic()
getStatusTopic()
getTelemetryTopic()
```

### PR DESCRIPTION
**Pull request by sumnerboy12**
@moinmoin-sh can you check this will meet your requirements?

### CODE REVIEW

**Comment by moinmoin-sh** [comment]
Looks good. Will try later.
I would display the CONFIG or STATUS topic. Which one do you prefer? It finally doesn't matter, will reserve just one line on the display for topic display.
May be we dont need the MACaddress display anymore?

**Comment by sumnerboy12** [comment]
I think the status topic. Config will hopefully be handled by a standalone application we are working on in parallel...

I think IP and MAC are useful, especially when first provisioning one of these. 

Could we show them for the first 10s or something and then revert to maker and version?

**Comment by moinmoin-sh** [comment]
agree with the status topic, had the same thought.

I don't like to display important information as IP on a splash screen only because it would require a boot to show this. I have no problem to show the MAC, just wanted to avoid redundent information

**Comment by sumnerboy12** [comment]
Yep fair point. What if we cycle between the two views every 5s? IP and MAC
in one view, maker and version in the other. Firmware name is constant on
the first line, the 2nd and 3rd lines change.

The maker icon is constant also.

So we only use 3 lines of ui real estate, the rest is available for the
firmware to show whatever it needs.

**Comment by moinmoin-sh** [comment]
I’m not a friend of blinking and constantly changing content. It also somehow conflicts with dimming/blanking an I think it makes it harder to focus on the real changes like button presses .

I would like to have a more static display as long as we don’t have space isues . May be this changes in future?

**Comment by sumnerboy12** [comment]
Fair enough, it is your baby, whatever you think looks best. Everything you
have done so far has been great so will leave it with you!

**Comment by sumnerboy12** [comment]
@moinmoin-sh if you are happy with this I will merge it

**Comment by moinmoin-sh** [comment]
That looks good! 
I just thought about to show MQTT activity (publish and receive) with "LED's" next to MQTT, A little similar to the RJ45 ethernet socket leds when they show activity. (This screen shot has still the interims header)
mqtt

**Review by moinmoin-sh — APPROVED** [review]

**Comment by sumnerboy12** [comment]
Ha - I love it! I will merge this now.

Just looking at that screenshot, it might be good to change `Rack Temp` -> `Temp` so all those labels are a similar width?

Otherwise looking really slick.

**Comment by moinmoin-sh** [comment]
> 
> 
> Just looking at that screenshot, it might be good to change `Rack Temp` -> `Temp` so all those labels are a similar width?
> 

done !

**Pull request merged**
